#!/bin/bash

_kill_procs() {
  kill -TERM $chrome
  wait $chrome
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

# Start Chrome inside xvfb
xvfb-run -a -s "-screen 0 1920x1080x24 -nolisten tcp" /opt/google/chrome/chrome --no-sandbox $@ &
chrome=$!

wait $chrome
